set-environment -g PATH "/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin"
set-option -sa terminal-overrides ",xterm*:Tc"
set -g mouse on


set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'


set-window-option -g xterm-keys on
set -s default-terminal "xterm-256color"


set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

bind x kill-pane

unbind C-b
set -g prefix C-space
bind C-space send-prefix


set -g status on
set -g status-position bottom
set -g status-style "bg=default"

set-option -g status 2
set-option -g status-format[0] ""
set-option -g status-format[1] " #[fg=#18354c,bg=default]#[fg=#419fff,bg=#18354c,bold] #S #[fg=#18354c,bg=default]"
set-option -ag status-format[1] "#{W:#{l:#[fg=black,bg=#18354c]#[fg=#419fff,bg=#18354c]} #I #W #{l:#[fg=#18354c,bg=default]},#{l:#[fg=black,bg=#419fff]#[fg=#18354c,bg=#419fff,bold]} #I #W #{l:#[fg=#419fff,bg=default]}}"

set -g window-status-separator ""

set -g pane-border-style "fg=#18354c"
set -g pane-active-border-style "fg=#419fff"

set -g mode-style "bg=#419fff,fg=#18354c,bold"
set -g cursor-style blinking-bar


run '~/.tmux/plugins/tpm/tpm'
